-- 1. PROPERTIES TABLE
CREATE TABLE IF NOT EXISTS properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  price NUMERIC DEFAULT 0,
  rent NUMERIC DEFAULT 0,
  due INTEGER DEFAULT 1,
  late_fee_day INTEGER DEFAULT 8,
  late_fee NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. UNITS TABLE
CREATE TABLE IF NOT EXISTS units (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prop_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  start_date DATE,
  end_date DATE,
  due INTEGER DEFAULT 1,
  late_fee_day INTEGER DEFAULT 8,
  late_fee_amt NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TENANTS TABLE
CREATE TABLE IF NOT EXISTS tenants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  share NUMERIC DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. TRANSACTIONS TABLE
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT CHECK (type IN ('income', 'expense')),
  date DATE NOT NULL,
  amount NUMERIC NOT NULL,
  property BIGINT REFERENCES properties(id) ON DELETE SET NULL,
  unit_id BIGINT REFERENCES units(id) ON DELETE SET NULL,
  category TEXT,
  vendor TEXT,
  description TEXT,
  source TEXT DEFAULT 'manual',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. VIOLATIONS TABLE
CREATE TABLE IF NOT EXISTS violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  prop_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
  type TEXT,
  date DATE NOT NULL,
  amount NUMERIC DEFAULT 0,
  code TEXT,
  status TEXT DEFAULT 'open',
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 6. PAYMENTS TABLE
CREATE TABLE IF NOT EXISTS payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_id BIGINT REFERENCES units(id) ON DELETE CASCADE,
  tenant_id BIGINT REFERENCES tenants(id) ON DELETE CASCADE,
  year INTEGER NOT NULL,
  month INTEGER NOT NULL,
  rent NUMERIC DEFAULT 0,
  previous_balance NUMERIC DEFAULT 0,
  late_fee NUMERIC DEFAULT 0,
  other NUMERIC DEFAULT 0,
  gas NUMERIC DEFAULT 0,
  electricity NUMERIC DEFAULT 0,
  water NUMERIC DEFAULT 0,
  inspection NUMERIC DEFAULT 0,
  total NUMERIC DEFAULT 0,
  received NUMERIC DEFAULT 0,
  remaining NUMERIC DEFAULT 0,
  payment_date DATE,
  payment_mode TEXT,
  status TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(unit_id, tenant_id, year, month)
);

-- Enable Row Level Security (RLS) - Optional but recommended
-- For now, let's keep it simple and assume public access if RLS is not configured yet.
-- ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
-- (Add policies here if needed)
